## Coding Exercise 0101

### 1. NumPy library:

#### 1.1. NumPy basics:

In [2]:
import numpy as np
np.__version__

'2.0.2'

In [3]:
arr1 = np.array([1,3,5,7,9])
arr2 = np.array((1,3,5,7,9))
type(arr1)

numpy.ndarray

In [4]:
arr3 = arr1

In [5]:
id(arr1)

133637887488528

In [6]:
id(arr3)

133637887488528

In [7]:
arr4 = arr1.copy()

In [8]:
id(arr4)

133637887488432

#### 1.2. Creating NumPy arrays:

numpy.arange() function:

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(10, 20, 3)

array([10, 13, 16, 19])

In [12]:
arr = np.arange(10)

In [13]:
len(arr)

10

In [14]:
arr.size

10

numpy.linspace() function:

In [15]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [17]:
arr = np.linspace(0, 10, 5, retstep=False)
type(arr)

numpy.ndarray

In [19]:
arr[0]

np.float64(0.0)

In [20]:
arr[1]

np.float64(2.5)

numpy.zeros() and numpy.ones() functions:

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.zeros(5, dtype ='int64')

array([0, 0, 0, 0, 0])

In [24]:
np.zeros(5, dtype ='int64').dtype

dtype('int64')

In [25]:
arr = np.ones((2,3), dtype ='int_')

In [26]:
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [27]:
arr.dtype

dtype('int64')

In [ ]:
arr.astype('float32')

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

Data type:

In [28]:
arr1 = np.array([111, 2.3,  True, False, False])
arr1

array([111. ,   2.3,   1. ,   0. ,   0. ])

In [29]:
arr2 = np.array([111, 2.3, 'python', 'abc'])
arr2

array(['111', '2.3', 'python', 'abc'], dtype='<U32')

In [31]:
arr3 = np.array([111, True, 'a'*20])
arr3

array(['111', 'True', 'aaaaaaaaaaaaaaaaaaaa'], dtype='<U21')

#### 1.3. Indexing and slicing NumPy arrays:

In [32]:
a = np.array([1, 2, 3, 4, 5])
a[2]

np.int64(3)

In [33]:
a[-1]

np.int64(5)

In [34]:
a[:]

array([1, 2, 3, 4, 5])

In [35]:
a = np.array([[1, 2, 3,], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
a[1]

array([4, 5, 6])

In [37]:
a[-1]

array([7, 8, 9])

In [38]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
a[2][1]

np.int64(8)

In [40]:
a[2,1]

np.int64(8)

In [41]:
a[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [42]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

Fancy indexing:

In [43]:
arr = np.arange(100)
arrMask = ( (arr % 5) == 0 )
arr[arrMask]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [44]:
arrMask = ( ( (arr % 5) == 0 )  & ( arr >0) )
arr[arrMask]

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

#### 1.4. NumPy attributes and reshaping:

In [45]:
a.size

9

In [46]:
a.shape

(3, 3)

In [47]:
a.ndim

2

Change the shape with reshape() method:

In [48]:
a = np.arange(15)
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
# reshape() just produced a 'view'.
# So, there is no permanent change to 'a'.
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [50]:
a = a.reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [51]:
a = np.array([2,5,1,3])
a.shape

(4,)

In [53]:
a.ndim

2

In [52]:
a = a.reshape((2,2))
a

array([[2, 5],
       [1, 3]])

Careful that the reshape() method does not create a new object!

In [54]:
a = np.arange(10)
b = a.reshape(2,5)
a[0] = -999

In [ ]:
b

array([[-999,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [55]:
# Make a copy in order to create a new object.
c = a.reshape(2,5).copy()
c[0,0] = 0
a

array([-999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

#### 1.5. Modifying NumPy arrays:

Appending elements, rows and columns to arrays:

In [56]:
a = np.array([1, 2, 3])
b = np.append(a, [4, 5, 6])
b

array([1, 2, 3, 4, 5, 6])

In [57]:
a = np.array([[1, 2], [3, 4]])
b = np.append(a, [[9, 9]], axis=0)
b

array([[1, 2],
       [3, 4],
       [9, 9]])

In [ ]:
c = np.append(a, [[9], [9]] , axis=1)
c

array([[1, 2, 9],
       [3, 4, 9]])

Deleting array elements, rows and columns:

In [ ]:
a = np.array([[1, 2, 3],[4, 5, 6]])
np.delete(a, 0)

array([2, 3, 4, 5, 6])

In [ ]:
np.delete(a, (0, 2, 4))

array([2, 4, 6])

In [ ]:
np.delete(a, 0, axis = 0)

array([[4, 5, 6]])

In [ ]:
np.delete(a, 1, axis = 1)

array([[1, 3],
       [4, 6]])